spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver       # mysql
    url: jdbc:mysql://localhost:3306/gulimall_ums?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 202095@Wrm
  application:
    name: gulimall-member
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos?????????

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000
