spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu #按照参数的方式

        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url, qq #按照参数的方式

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}

#前端项目， /api 前缀
# 对gateway请求转发路径 url的分析
# 转发后的地址 http://localhost:88/api/captcha.jpg?uuid=db8aa62e-0eb8-4ed5-87fc-726b34ead264
# http://localhost:8080/renren-fast/captcha.jpg?uuid=db8aa62e-0eb8-4ed5-87fc-726b34ead264







